### ISSUE TITLE
`SellerRequestedCancellationSimulateAction` is not updating Orders feed

### ISSUE THREAD

**Issue by nickevansuk** [playfinder/openactive#6]
A successful call to `SellerRequestedCancellationSimulateAction` does not update the Orders feed

- [seller-requested-cancellation_seller-requested-cancellation_OpenBookingSimpleFlow_IndividualFacilityUseSlot.md](https://github.com/playfinder/openactive/files/14087834/seller-requested-cancellation_seller-requested-cancellation_OpenBookingSimpleFlow_IndividualFacilityUseSlot.md)
- [order-deletion_orders-updated-then-deleted_OpenBookingSimpleFlow_IndividualFacilityUseSlot.md](https://github.com/playfinder/openactive/files/14087835/order-deletion_orders-updated-then-deleted_OpenBookingSimpleFlow_IndividualFacilityUseSlot.md)

**Comment by nathansalter** [comment]
This was to do with the permissions not working properly with oauth instead of key-based auth. It should be resolved now, but does come with the caveat that separate credentials will no longer return information by broker. This means that if you mint a new OAuth id/secret pair, you could lose access to the existing Orders.
